SETTING_PHOTOFILENAME = 'photofilename'
SETTING_RECENT_FILES = 'recentFiles'
SETTING_WIN_SIZE = 'window/size'
SETTING_WIN_POSE = 'window/position'
SETTING_WIN_GEOMETRY = 'window/geometry'
SETTING_LINE_COLOR = 'line/color'
SETTING_FILL_COLOR = 'fill/color'
SETTING_ADVANCE_MODE = 'advanced'
SETTING_WIN_STATE = 'window/state'
SETTING_SAVE_DIR = 'savedir'
SETTING_LAST_CAN_OPEN_DIR = 'lastCanOpenDir'
SETTING_LAST_PHOTO_OPEN_DIR = 'lastPhotoOpenDir'
SETTING_LAST_LIDAR_OPEN_DIR = 'lastLidarOpenDir'

SETTING_AUTO_SAVE = 'autosave'
SETTING_SINGLE_CLASS = 'singleclass'